import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
const require=createRequire(import.meta.url),{chromium}=require(process.env.DERMIS_PLAYWRIGHT_PATH||'playwright');
const out=resolve(process.env.DERMIS_QA_DIR||'docs/current');await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.DERMIS_BROWSER?{executablePath:process.env.DERMIS_BROWSER}:{channel:'msedge'}),args:['--enable-unsafe-webgpu']});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));
const check=(name,condition)=>{assert.ok(condition,name);checks.push(name);console.log('PASS '+name);};
try{
 await page.goto(process.env.DERMIS_URL||'http://localhost:8080');await page.waitForFunction(()=>window.dermisApp);
 await page.selectOption('#quality','extreme');await page.click('#initialize');
 await page.waitForFunction(()=>window.dermis?.samples>=24||!document.querySelector('#error').hidden,{},{timeout:120000});
 check('Stress initializes without dispatch errors',!await page.locator('#error').isVisible());
 check('Actual anatomical mesh and 100,000 scalp strands loaded',await page.evaluate(()=>!!dermis.anatomySource&&dermis.stats().scalpStrands===100000));
 const before=await page.evaluate(()=>({...dermis.config}));await page.selectOption('#stress-duration','15');await page.click('#stress-toggle');
 check('Quality is locked during a timed test',await page.locator('#quality-section').evaluate(e=>e.inert));
 await page.waitForFunction(()=>dermisApp.stressReport?.reason==='completed',{},{timeout:60000});
 const report=await page.evaluate(()=>dermisApp.stressReport);
 check('Timed run completes with measured frames and eight spatial samples',report.frames>10&&report.elapsedSeconds>=15&&report.samples===8);
 assert.deepEqual(await page.evaluate(()=>({...dermis.config})),before);checks.push('Authored settings restored after completion');
 const dl=page.waitForEvent('download');await page.click('#stress-export');await(await dl).saveAs(resolve(out,'stress-test-report.json'));
 await page.click('#stress-toggle');await page.waitForTimeout(600);await page.click('#stress-toggle');
 check('Stop cancels a live run',await page.evaluate(()=>dermisApp.stressReport.reason==='stopped'));
 assert.deepEqual(await page.evaluate(()=>({...dermis.config})),before);
 await page.selectOption('#quality','balanced');await page.waitForFunction(()=>dermis.config.quality==='balanced'&&dermis.samples>=24);
 const geometry=await page.evaluate(()=>({v:dermis.layout.vertices,w:dermis.width,h:dermis.height}));
 await page.click('#animate');await page.waitForFunction(()=>dermis.config.animation&&dermis.frameSamples===4&&dermis.frames>200);
 check('Living portrait preserves mesh and resolution',await page.evaluate(g=>g.v===dermis.layout.vertices&&g.w===dermis.width&&g.h===dermis.height,geometry));
 await page.screenshot({path:resolve(out,'living-portrait.png')});await page.click('#animate');await page.waitForFunction(()=>dermis.samples>=24);
 const screenshot=async(name,patch)=>{await page.evaluate(p=>dermisApp.change(p),patch);await page.waitForFunction(()=>dermis.samples>=24);const data=await page.evaluate(async()=>{const a=await dermis.pixels(),c=document.createElement('canvas');c.width=dermis.width;c.height=dermis.height;c.getContext('2d').putImageData(new ImageData(Uint8ClampedArray.from(a,x=>Math.round(x*255)),c.width,c.height),0,0);return c.toDataURL().split(',')[1];});await writeFile(resolve(out,name+'.png'),Buffer.from(data,'base64'));};
 for(const [name,patch]of [['front',{orbitYaw:0,orbitPitch:0}],['profile',{orbitYaw:Math.PI/2}],['three-quarter',{orbitYaw:.63}],['top',{orbitYaw:.63,orbitPitch:.9}],['rear',{orbitYaw:Math.PI,orbitPitch:.2}],['closed-eyes',{orbitYaw:0,orbitPitch:0,blink:.98}],['bald',{blink:.02,hair:false}],['expressions',{hair:true,smile:1,jaw:1.3,nose:1.25}]])await screenshot(name,patch);
 check('Facial-control extremes produce finite positions and normals',await page.evaluate(async()=>{const p=await dermis.rt.read(dermis.positions),n=await dermis.rt.read(dermis.normals);return p.every(Number.isFinite)&&n.every(Number.isFinite)&&!dermis.fatal;}));
 await page.setViewportSize({width:2398,height:2109});await page.selectOption('#quality','extreme');
 await page.waitForFunction(()=>dermis.config.quality==='extreme'&&dermis.width===2000&&dermis.height===2000&&dermis.samples>=24,{},{timeout:90000});
 check('Maximum square stress framebuffer fits compute dispatch limits',await page.evaluate(()=>!dermis.fatal));
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>dermis.height===753&&dermis.samples>=24);
 check('Mobile viewport retains its display aspect ratio',await page.evaluate(()=>Math.abs(dermis.displayAspect-335/753)<1e-6));
 check('No uncaught browser errors',errors.length===0);
 await writeFile(resolve(out,'browser-validation.json'),JSON.stringify({date:new Date().toISOString(),checks,errors,report},null,2));
}finally{await browser.close();}

