import {writeFile} from 'node:fs/promises';import {nativeGpu} from './native.mjs';import {PRESENT} from '../src/bridge.js';
const gpu=await nativeGpu(),adapter=await gpu.requestAdapter(),device=await adapter.requestDevice(),checks=[],errors=[];device.addEventListener('uncapturederror',e=>errors.push(e.error.message));
const check=(name,passed)=>{checks.push({name,passed:!!passed});console.log((passed?'PASS ':'FAIL ')+name);if(!passed)throw Error(name);};
try{
 const width=64,height=16,data=new Float32Array(width*height*4);for(let y=0;y<height;y++)for(let x=0;x<width;x++)data.set([x/(width-1),y/(height-1),(x%7)/6,1],(y*width+x)*4);
 const pixels=device.createBuffer({size:data.byteLength,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(pixels,0,data);const info=device.createBuffer({size:16,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(info,0,new Uint32Array([width,height,0,0]));
 const module=device.createShaderModule({code:PRESENT});const compilation=await module.getCompilationInfo();check('Actual presentation WGSL compiles without shader errors',!compilation.messages.some(m=>m.type==='error'));
 for(const format of ['rgba8unorm','bgra8unorm']){
  const pipeline=await device.createRenderPipelineAsync({layout:'auto',vertex:{module,entryPoint:'vertex'},fragment:{module,entryPoint:'fragment',targets:[{format}]},primitive:{topology:'triangle-list'}});const bind=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:pixels}},{binding:1,resource:{buffer:info}}]});
  const texture=device.createTexture({size:[width,height],format,usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.COPY_SRC}),read=device.createBuffer({size:width*height*4,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});
  const encoder=device.createCommandEncoder(),pass=encoder.beginRenderPass({colorAttachments:[{view:texture.createView(),clearValue:{r:0,g:0,b:0,a:0},loadOp:'clear',storeOp:'store'}]});pass.setPipeline(pipeline);pass.setBindGroup(0,bind);pass.draw(3);pass.end();encoder.copyTextureToBuffer({texture},{buffer:read,bytesPerRow:width*4,rowsPerImage:height},[width,height]);device.queue.submit([encoder.finish()]);await read.mapAsync(GPUMapMode.READ);const bytes=new Uint8Array(read.getMappedRange());let maxError=0;for(let i=0;i<width*height;i++)for(let c=0;c<4;c++){const src=format==='bgra8unorm'&&c<3?2-c:c;maxError=Math.max(maxError,Math.abs(bytes[i*4+c]-Math.round(data[i*4+src]*255)));}check(format+' presentation preserves colours, orientation and dimensions within 1 byte',maxError<=1);read.unmap();read.destroy();texture.destroy();
 }
 check('No uncaptured native presentation errors',errors.length===0);pixels.destroy();info.destroy();
}catch(error){console.error(error);process.exitCode=1;}finally{await writeFile(new URL('../docs/presentation-validation.json',import.meta.url),JSON.stringify({passed:checks.filter(c=>c.passed).length,total:checks.length,backend:adapter.info,checks,errors,limitation:'Actual presentation shader rendered to offscreen GPU textures. Browser compositor presentation remains unverified.'},null,2));device.destroy();}process.exit(process.exitCode||0);
