import {PortraitEngine} from './engine.js';
import {DEFAULTS,RANGES,validateConfig} from './config.js';
import {clamp} from './math.js';
import {StressRun} from './stress.js';
let stressRun=null,stressSaved=null,stressReport=null,lastEdit=0;
const $=id=>document.getElementById(id),canvas=$('portrait'),viewport=$('viewport');
let config={...DEFAULTS},engine=null,busy=false,starting=false,alive=true,sourceTab='human',sources=null,lastTime=0,simTime=0,pendingResize=true,frames=0,millis=0,toastTimer;
const sections=[
 ['01','Skin',true,[['melanin','Pigment',.01],['roughness','Surface roughness',.01],['scattering','Subsurface diffusion',.01],['detail','Pores & variation',.05]]],
 ['02','Eyes',true,[['iris','Iris colour','select'],['pupil','Pupil radius',.01],['gazeX','Look left / right',.02],['gazeY','Look down / up',.02]]],
 ['03','Hair',true,[['hairMelanin','Pigment',.01],['hairRoughness','Longitudinal roughness',.02],['hairLength','Fiber length',.02],['breeze','Breeze',.02],['hair','Show scalp hair','check']]],
 ['04','Expression & form',false,[['smile','Smile',.02],['blink','Close eyelids',.01],['brow','Brow lift',.02],['jaw','Jaw width',.01],['nose','Nose projection',.01]]],
 ['05','Studio lighting',false,[['lightAngle','Key-light orbit',1],['lightPower','Key-light power',.05],['exposure','Exposure',.02]]]
];
for(const [number,title,open,fields]of sections){const details=document.createElement('details');details.open=open;const summary=document.createElement('summary');summary.innerHTML=`<span><span class="section-num">${number}</span>${title}</span>`;details.append(summary);const group=document.createElement('div');group.className='control-group';
 for(const [key,label,step]of fields){const div=document.createElement('div');div.className=step==='check'?'check-field':'range-field';const name=document.createElement('label');name.htmlFor=key;name.textContent=label;
  if(step==='select'){const select=document.createElement('select');select.id=key;['Blue / slate','Green / olive','Hazel / amber','Dark brown'].forEach((n,i)=>select.add(new Option(n,i)));div.append(name,select);select.addEventListener('change',()=>change({[key]:Number(select.value)}));}
  else if(step==='check'){const input=document.createElement('input');input.type='checkbox';input.id=key;div.append(name,input);input.addEventListener('change',()=>change({[key]:input.checked}));}
  else{const output=document.createElement('output');output.id=key+'-value';name.append(output);const range=document.createElement('input');range.type='range';range.id=key;range.min=RANGES[key][0];range.max=RANGES[key][1];range.step=step;div.append(name,range);range.addEventListener('input',()=>change({[key]:Number(range.value)}));}group.append(div);
 }details.append(group);$('control-sections').append(details);
}
function syncUI(){for(const [key,value]of Object.entries(config)){const input=$(key);if(input){if(input.type==='checkbox')input.checked=value;else input.value=value;const output=$(key+'-value');if(output){output.value=Number(value).toFixed(key==='lightAngle'?0:2);input.style.setProperty('--value',((value-Number(input.min))/(Number(input.max)-Number(input.min))*100)+'%');}}}
 $('animate').setAttribute('aria-pressed',String(config.animation));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.view)===config.view));}
function change(patch){if(stressRun)return;lastEdit=performance.now();try{config=validateConfig({...config,...patch});engine?.update(patch);syncUI();}catch(e){toast(e.message);}}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
function error(err){console.error(err);$('status').textContent='RENDERER STOPPED';$('error').hidden=false;$('error').textContent=err.message||String(err);}
async function source(){if(!sources){const load=async path=>{const r=await fetch(path);if(!r.ok)throw Error('Unable to load '+path+' ('+r.status+').');return r.text();};sources={human:await load('kernels/human.cu'),appearance:await load('kernels/appearance.cu'),realism:await load('kernels/realism.cu'),anatomy:JSON.parse(await load('assets/male-anatomy.json'))};}return sources;}
async function initialize(){if(starting||engine)return;starting=true;$('initialize').disabled=true;try{if(!navigator.gpu)throw Error('WebGPU is unavailable. Use a WebGPU-enabled browser with hardware acceleration on localhost or HTTPS. Opening index.html directly will not work.');const s=await source();engine=await PortraitEngine.create({canvas,...s,appearance:s.realism+'\n'+s.appearance,config,progress:t=>{$('progress').textContent=t;}});window.dermis=engine;$('welcome').style.display='none';$('error').hidden=true;$('capture-button').disabled=false;$('stress-toggle').disabled=false;$('status').textContent='CUDA PIPELINE ACTIVE';const gpu=engine.rt.describe();$('gpu-name').textContent=[gpu.vendor,gpu.architecture].filter(Boolean).join(' · ')||'WebGPU adapter';pendingResize=true;requestAnimationFrame(loop);}catch(e){error(e);engine=null;$('progress').textContent='Initialization failed — details are shown below.';$('initialize').disabled=false;}finally{starting=false;}}
function resize(){if(!engine)return;const rect=viewport.getBoundingClientRect(),max={preview:640,balanced:1100,high:1600,stress:2000,extreme:2000}[config.quality],scale=Math.min(devicePixelRatio||1,max/Math.max(rect.width,rect.height));engine.resize(Math.max(64,Math.round(rect.width*scale)),Math.max(64,Math.round(rect.height*scale)));pendingResize=false;}
async function loop(now){if(!alive||!engine)return;if(!busy&&!document.hidden&&(engine.samples<24||config.animation||stressRun||pendingResize)){busy=true;try{if(pendingResize)resize();const dt=Math.min(.05,Math.max(0,(now-lastTime)/1000));if(config.animation||stressRun)simTime+=dt;lastTime=now;const start=performance.now();if(stressRun){engine.geometryDirty=true;engine.sceneDirty=true;engine.samples=0;}engine.renderFrame(simTime,{motion:!!stressRun||now-lastEdit<180});await engine.rt.idle();const duration=performance.now()-start;frames++;millis+=duration;const s=engine.stats();$('sample-count').textContent=config.animation?`${(1000/duration).toFixed(1)} fps · ${engine.frameSamples} samples/frame`:`${Math.min(s.samples,24)} / 24 samples`;$('render-state').textContent=config.animation?'LIVE · CUDA':'ACCUMULATING';if(!config.animation&&s.samples>=24)$('render-state').textContent='CONVERGED';$('metrics').textContent=`${s.width} × ${s.height} · ${(s.triangles/1000).toFixed(0)}k triangles · ${s.scalpStrands.toLocaleString()} scalp strands · ${s.bufferMiB.toFixed(0)} MiB buffers`;if(engine.fatal)throw engine.fatal;if(stressRun){const done=stressRun.record(duration);showStress();$('render-state').textContent='STRESS TEST';if(done)stopStress('completed');}}catch(e){if(stressRun)stopStress('failed',e.message);error(e);alive=false;}finally{busy=false;}}requestAnimationFrame(loop);}
$('initialize').addEventListener('click',initialize);$('mobile-controls').addEventListener('click',()=>$('inspector').classList.toggle('mobile-open'));
$('animate').addEventListener('click',()=>{change({animation:!config.animation});lastTime=performance.now();});
$('quality').addEventListener('change',async()=>{if(stressRun)return;const quality=$('quality').value;if(!engine){config=validateConfig({...config,quality});return;}while(busy)await new Promise(r=>setTimeout(r,10));busy=true;try{$('status').textContent='REBUILDING GEOMETRY';await engine.setQuality(quality);config={...engine.config};pendingResize=true;syncUI();$('error').hidden=true;if(!alive){alive=true;requestAnimationFrame(loop);}$('status').textContent='CUDA PIPELINE ACTIVE';}catch(e){error(e);}finally{busy=false;}});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>change({view:Number(b.dataset.view)})));
const cameras={portrait:{orbitYaw:.1,orbitPitch:.025,distance:6.4,targetY:.12},face:{orbitYaw:0,orbitPitch:0,distance:4.6,targetY:.18},eye:{orbitYaw:0,orbitPitch:0,distance:2.5,targetY:.335},threequarter:{orbitYaw:.63,orbitPitch:.02,distance:6.4,targetY:.12},profile:{orbitYaw:Math.PI/2,orbitPitch:0,distance:6.4,targetY:.12}};
function camera(name){change(cameras[name]);document.querySelectorAll('[data-camera]').forEach(b=>b.classList.toggle('active',b.dataset.camera===name));}
document.querySelectorAll('[data-camera]').forEach(b=>b.addEventListener('click',()=>camera(b.dataset.camera)));
const looks={reference:{melanin:DEFAULTS.melanin,iris:DEFAULTS.iris,hairMelanin:DEFAULTS.hairMelanin,hairRoughness:DEFAULTS.hairRoughness,hairLength:DEFAULTS.hairLength,roughness:DEFAULTS.roughness,scattering:DEFAULTS.scattering,detail:DEFAULTS.detail},neutral:{melanin:.23,iris:2,hairMelanin:.9},warm:{melanin:.36,iris:2,hairMelanin:.95},dark:{melanin:.76,iris:3,hairMelanin:1},blonde:{melanin:.05,iris:0,hairMelanin:.20}};
document.querySelectorAll('[data-look]').forEach(b=>b.addEventListener('click',()=>{change(looks[b.dataset.look]);document.querySelectorAll('[data-look]').forEach(x=>x.classList.toggle('active',x===b));$('look-name').textContent=b.title;}));
$('reset-look').addEventListener('click',()=>{const quality=config.quality;change({...DEFAULTS,quality});document.querySelectorAll('[data-look]').forEach(b=>b.classList.toggle('active',b.dataset.look==='reference'));$('look-name').textContent='Reference · short blond';camera('portrait');toast('Portrait settings reset.');});
let pointer=null;canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(!engine)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,button:e.button};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;pointer.x=e.clientX;pointer.y=e.clientY;if(pointer.button===2||e.shiftKey)change({targetY:clamp(config.targetY+dy*.004,-1.5,1.5)});else change({orbitYaw:clamp(config.orbitYaw-dx*.006,-Math.PI,Math.PI),orbitPitch:clamp(config.orbitPitch+dy*.006,-.9,.9)});});
for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,()=>{pointer=null;});canvas.addEventListener('wheel',e=>{if(!engine)return;e.preventDefault();change({distance:clamp(config.distance*Math.exp(e.deltaY*.001),2.3,12)});},{passive:false});canvas.addEventListener('dblclick',()=>camera('face'));
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement?.tagName)||$('source-dialog').open)return;if(e.code==='Space'){e.preventDefault();$('animate').click();}if(e.key.toLowerCase()==='r')camera('portrait');if(e.key.toLowerCase()==='f')camera('face');});
new ResizeObserver(()=>{pendingResize=true;}).observe(viewport);document.addEventListener('visibilitychange',()=>{lastTime=performance.now();if(document.hidden&&stressRun)stopStress('tab hidden');});window.addEventListener('beforeunload',()=>{alive=false;engine?.dispose();});
function download(name,blob){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
$('save-button').addEventListener('click',()=>{download('dermis-look.json',new Blob([JSON.stringify({format:'dermis-look',version:1,config},null,2)],{type:'application/json'}));toast('Saved editable portrait settings.');});
$('load-button').addEventListener('click',()=>$('load-file').click());$('load-file').addEventListener('change',async()=>{const file=$('load-file').files[0];if(!file)return;try{if(file.size>1048576)throw Error('Look files must be smaller than 1 MB.');const data=JSON.parse(await file.text());if(data.format!=='dermis-look'||data.version!==1)throw Error('Not a supported DERMIS look file.');const next=validateConfig(data.config);if(engine&&next.quality!==config.quality){while(busy)await new Promise(r=>setTimeout(r,10));busy=true;try{await engine.setQuality(next.quality);}finally{busy=false;}}config=next;engine?.update(next);pendingResize=true;syncUI();toast('Look restored.');}catch(e){toast(e.message);}finally{$('load-file').value='';}});
$('capture-button').addEventListener('click',async()=>{if(!engine)return;try{while(busy)await new Promise(r=>setTimeout(r,10));busy=true;const data=await engine.pixels(),w=engine.width,h=engine.height,out=document.createElement('canvas');out.width=w;out.height=h;const bytes=new Uint8ClampedArray(w*h*4);for(let i=0;i<bytes.length;i++)bytes[i]=Math.round(clamp(data[i],0,1)*255);out.getContext('2d').putImageData(new ImageData(bytes,w,h),0,0);out.toBlob(blob=>{if(blob)download('dermis-portrait.png',blob);},'image/png');toast('Captured the actual CUDA-rendered framebuffer.');}catch(e){toast(e.message);}finally{busy=false;}});
async function showSource(tab='human'){try{sourceTab=tab;const s=await source();$('source-code').textContent=s[tab];document.querySelectorAll('[data-source]').forEach(b=>b.classList.toggle('selected',b.dataset.source===tab));if(!$('source-dialog').open)$('source-dialog').showModal();}catch(e){toast(e.message);}}
$('source-button').addEventListener('click',()=>showSource());$('close-source').addEventListener('click',()=>$('source-dialog').close());document.querySelectorAll('[data-source]').forEach(b=>b.addEventListener('click',()=>showSource(b.dataset.source)));$('download-source').addEventListener('click',async()=>download(sourceTab+'.cu',new Blob([(await source())[sourceTab]],{type:'text/plain'})));
function stressControls(active){
 for(const id of ['control-sections','quality-section','look-section','motion-section'])$(id).inert=active;
 for(const id of ['reset-look','load-button','save-button','capture-button','stress-duration'])$(id).disabled=active;
 $('stress-toggle').textContent=active?'Stop test':'Start stress test';$('stress-toggle').setAttribute('aria-pressed',String(active));
}
function showStress(){
 const s=stressRun?.summary()??stressReport;if(!s)return;
 $('stress-results').textContent=`${s.reason} · ${s.elapsedSeconds.toFixed(1)} s · ${s.frames} frames\n${s.fps.toFixed(1)} FPS · mean ${s.meanRenderMs.toFixed(1)} ms · p95 ${s.p95RenderMs.toFixed(1)} ms`;
}
function stopStress(reason='stopped',message=''){
 if(!stressRun)return;stressRun.stop(reason);stressReport={...stressRun.summary(),message,date:new Date().toISOString(),quality:config.quality,...engine.stats(),timing:'FPS includes browser frame scheduling. Render milliseconds measure CPU submission plus GPU queue completion, not hardware GPU timestamps.'};
 // Preserve benchmark frame count rather than the engine lifetime count.
 stressReport.frames=stressRun.summary().frames;stressRun=null;
 engine.update(stressSaved);stressSaved=null;stressControls(false);$('stress-export').disabled=false;showStress();lastTime=performance.now();
}
async function startStress(){
 if(!engine||!alive||stressRun)return;while(busy)await new Promise(r=>setTimeout(r,10));
 if(stressRun)return;stressSaved={...engine.config};engine.update({animation:true,breeze:Math.max(.35,config.breeze)});
 stressRun=new StressRun(Number($('stress-duration').value));stressControls(true);$('stress-export').disabled=true;lastTime=performance.now();showStress();
}
$('stress-toggle').addEventListener('click',()=>{if(stressRun)stopStress();else startStress();});
$('stress-export').addEventListener('click',()=>{if(stressReport)download('dermis-stress-report.json',new Blob([JSON.stringify(stressReport,null,2)],{type:'application/json'}));});
syncUI();window.dermisApp={initialize,startStress,stopStress,get stressReport(){return stressReport;},get config(){return config;},change,camera};
// Useful for automated testing and direct-link looks; still uses the full application.
if(new URLSearchParams(location.search).has('autostart'))initialize();



